sudo: required
addons:
  chrome: stable
language: node_js
node_js: stable
cache:
  directories:
    - node_modules
script:
  - google-chrome-stable --version
  - npm run lerna:bootstrap
  - npm run lerna:test
